### ISSUE TITLE
RSSI of mesh messages

### ISSUE THREAD

**Issue by vliedel** [NordicSemiconductor/nRF51-ble-bcast-mesh#70] opened 2016-02-23 08:13 UTC
I was wondering if it's possible to get the RSSI of each mesh message and if so, at what cost?

**Comment by daviddedwin** [comment] 2016-03-01 14:53
Duplicate of #66

**Closed as completed by daviddedwin** 2016-03-01 14:53 UTC
Labels: enhancement

**Comment by vliedel** [comment] 2016-03-01 16:18
Ah sorry for the duplicate, nr 66 wasn't that clear to me :) Thanks!
